Домашняя работа по теме MySQL DML
HappyM0nk/OTUS_DB pull request #8
Opened 2024-07-20 18:38 UTC by HappyM0nk

2024-07-20 19:15 UTC, sov-87 requested changes

2024-07-20 19:15 UTC, sov-87 commented on homework/12_MySQL_DML/12_MySQL_DML.md
> +```sql
в этом запросе нет выборки

2024-07-20 19:15 UTC, sov-87 commented on homework/12_MySQL_DML/12_MySQL_DML.md
> +select * from
это классика для `having`

2024-07-21 04:13 UTC, HappyM0nk commented on homework/12_MySQL_DML/12_MySQL_DML.md
> +```sql
Изменил на запрос с выборкой

2024-07-21 04:14 UTC, HappyM0nk commented on homework/12_MySQL_DML/12_MySQL_DML.md
> +select * from
Да, я знаю. Но в задании было условие использовать WHERE, а не построить оптимальный запрос. Всё по ТЗ :). Добавил аналогичный запрос с HAVING.

2024-07-25 16:51 UTC, merged